name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

env:

  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt install rpm
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Create deb package
      working-directory: ${{github.workspace}}/build
      run: cpack
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0
        name: v1.0
        files: |
          build/*.deb
          build/*.rpm